### ISSUE TITLE
Demo Editor does not use 100% of browser window

### ISSUE THREAD

**Issue by jarradraumati** [OMICRONEnergyOSS/open-scd-core#7]
When `<!DOCTYPE html>` was added to the demo index.html, this disabled quirks mode. The impact of this is the editor not using all of the browser window.

![image](https://github.com/OMICRONEnergyOSS/open-scd-core/assets/3224671/6db86b7d-d94e-491a-885e-92b21dfde7e0)

Adding height of 100% to the html and body tags seems to resolve this.

```css
html, body {
  height: 100%;
}
```

This probably won't be a problem for `open-scd-core`, but distribution creators need to be aware of using `<!DOCTYPE html>`.

**Comment by ca-d** [comment]
Thanks for the hint, the fix has been applied.
